// Command docgen writes the reference pages under docs/reference/ from the
// Go source of truth (keymap.Default, the palette, the settings rows and
// the config file list), so the docs can never fall behind the code.
//
//	go run ./cmd/docgen          # write the files
//	go run ./cmd/docgen -check   # exit 1 if any file is out of date
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/amin-jalali/termocode/internal/app"
	"github.com/amin-jalali/termocode/internal/keymap"
)

// outDir is where the pages go, relative to the repository root.
const outDir = "docs/reference"

const banner = "<!-- Generated by `go run ./cmd/docgen` — do not edit by hand. -->\n\n"

func main() {
	check := flag.Bool("check", false, "exit non-zero if any generated file would change")
	root := flag.String("root", ".", "repository root")
	flag.Parse()

	stale, err := run(*root, *check)
	if err != nil {
		fmt.Fprintln(os.Stderr, "docgen:", err)
		os.Exit(1)
	}
	if *check && len(stale) > 0 {
		fmt.Fprintf(os.Stderr, "docgen: out of date: %s\nRun `go run ./cmd/docgen` and commit the result.\n", strings.Join(stale, ", "))
		os.Exit(1)
	}
}

// run renders every page. With check it only compares; otherwise it
// writes the changed files. It returns the paths that differ(ed).
func run(root string, check bool) ([]string, error) {
	pages := render()
	names := make([]string, 0, len(pages))
	for n := range pages {
		names = append(names, n)
	}
	sort.Strings(names)
	var stale []string
	for _, n := range names {
		path := filepath.Join(root, outDir, n)
		old, _ := os.ReadFile(path)
		if bytes.Equal(old, []byte(pages[n])) {
			continue
		}
		stale = append(stale, filepath.ToSlash(filepath.Join(outDir, n)))
		if check {
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return nil, err
		}
		if err := os.WriteFile(path, []byte(pages[n]), 0o644); err != nil {
			return nil, err
		}
	}
	return stale, nil
}

// render returns file name → content for every page.
func render() map[string]string {
	return map[string]string{
		"keys.md":         renderKeys(),
		"commands.md":     renderCommands(),
		"settings.md":     renderSettings(),
		"config-files.md": renderConfigFiles(),
	}
}

// ── Markdown helpers ────────────────────────────────────────────────────

// code renders s as inline code that is safe inside a table cell. Pipes
// and backticks can not live in a backtick span in a table, so those use
// an HTML <code> element with entities.
func code(s string) string {
	if s == "" {
		return ""
	}
	if !strings.ContainsAny(s, "|`\\") {
		return "`" + s + "`"
	}
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", "|", "&#124;", "`", "&#96;", "\\", "&#92;")
	return "<code>" + r.Replace(s) + "</code>"
}

// cell escapes plain text for a table cell.
func cell(s string) string {
	return strings.NewReplacer("|", "\\|", "\n", " ").Replace(s)
}

type table struct {
	b    *strings.Builder
	cols int
}

func newTable(b *strings.Builder, head ...string) table {
	b.WriteString("| " + strings.Join(head, " | ") + " |\n|")
	for range head {
		b.WriteString(" --- |")
	}
	b.WriteString("\n")
	return table{b: b, cols: len(head)}
}

func (t table) row(cells ...string) {
	for i, c := range cells {
		if c == "" {
			cells[i] = " "
		}
	}
	t.b.WriteString("| " + strings.Join(cells, " | ") + " |\n")
}

func humanKeys(keys []string) string {
	// Several key strings can name the same key ("alt+T", "alt+shift+t"),
	// so list each human name once.
	var out []string
	seen := map[string]bool{}
	for _, k := range keys {
		h := keymap.HumanKey(k)
		if !seen[h] {
			seen[h] = true
			out = append(out, code(h))
		}
	}
	return strings.Join(out, " / ")
}

// ── keys.md ─────────────────────────────────────────────────────────────

func renderKeys() string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("# Keyboard shortcuts\n\n")
	b.WriteString("These are the default keys. The **Key** column is the key you press. " +
		"The **Key string** column is the name termocode uses in `keymap.json`.\n\n")
	b.WriteString("!!! note \"Your terminal may take some keys\"\n" +
		"    Some keys never reach termocode because the terminal uses them " +
		"(for example `Ctrl+Shift+T`, `Ctrl+Shift+W`, `F11`). " +
		"That is why some actions have more than one key. " +
		"Every action is also in the command palette (`F1`).\n\n")

	km := keymap.Default()
	bindings := km.Bindings()
	type row struct {
		key string
		act keymap.Action
	}
	byArea := map[string][]row{}
	for k, a := range bindings {
		area := keymap.Describe(a).Area
		byArea[area] = append(byArea[area], row{k, a})
	}
	for _, area := range keymap.Areas {
		rows := byArea[area]
		if len(rows) == 0 {
			continue
		}
		sort.Slice(rows, func(i, j int) bool {
			ni, nj := keymap.ActionName(rows[i].act), keymap.ActionName(rows[j].act)
			if ni != nj {
				return ni < nj
			}
			return rows[i].key < rows[j].key
		})
		fmt.Fprintf(&b, "## %s\n\n", area)
		t := newTable(&b, "Key", "Key string", "Action", "Description")
		for _, r := range rows {
			t.row(code(keymap.HumanKey(r.key)), code(r.key), code(keymap.ActionName(r.act)), cell(keymap.Describe(r.act).Description))
		}
		b.WriteString("\n")
	}

	// Actions with no default key.
	var unbound []keymap.Action
	for _, a := range keymap.AllActions() {
		if len(km.KeysFor(a)) == 0 {
			unbound = append(unbound, a)
		}
	}
	if len(unbound) > 0 {
		b.WriteString("## Actions without a default key\n\n")
		b.WriteString("You can give these a key in `keymap.json` (see below), or run them from the command palette.\n\n")
		t := newTable(&b, "Action", "Area", "Description")
		for _, a := range unbound {
			info := keymap.Describe(a)
			t.row(code(keymap.ActionName(a)), cell(info.Area), cell(info.Description))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Editor keys (Neovim)\n\n")
	b.WriteString("The editor is real Neovim. termocode adds these keys inside Neovim. " +
		"They are not in `keymap.json`; change them with your own Neovim config. " +
		"All normal Vim keys work too.\n\n")
	t := newTable(&b, "Key", "Mode", "Description")
	for _, k := range app.EditorKeyCatalog() {
		t.row(code(k.Key), cell(k.Mode), cell(k.Description))
	}
	b.WriteString("\n")

	b.WriteString("## Change a key\n\n")
	b.WriteString("Use **Preferences: Customize Keybindings** in the palette, or edit " +
		"`~/.config/termocode/keymap.json` (or `$XDG_CONFIG_HOME/termocode/keymap.json`). " +
		"The file maps a key string to an action name from the tables above:\n\n")
	b.WriteString("```json\n{\n  \"alt+s\": \"Save\",\n  \"alt+h\": \"ext:hello.say\"\n}\n```\n\n")
	b.WriteString("Rules:\n\n")
	b.WriteString("- The key string must be one of the key strings in the tables above. Other keys are ignored.\n")
	b.WriteString("- A new entry takes the key from its old action. The old action keeps its other keys.\n")
	b.WriteString("- A value `\"ext:<command id>\"` runs an extension command. For these, any key string works.\n")
	b.WriteString("- Unknown action names are ignored. A broken file never stops termocode from starting.\n")
	return b.String()
}

// ── commands.md ─────────────────────────────────────────────────────────

func renderCommands() string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("# Command palette\n\n")
	b.WriteString("Open the palette with `F1` and type a few letters of a command. " +
		"**Key** is the default key from the keymap. **Hint** is the text the palette shows on the right.\n\n")

	byGroup := map[string][]app.PaletteEntry{}
	for _, e := range app.PaletteCatalog() {
		g := "General"
		if i := strings.Index(e.Title, ": "); i > 0 {
			g = e.Title[:i]
		}
		byGroup[g] = append(byGroup[g], e)
	}
	groups := make([]string, 0, len(byGroup))
	for g := range byGroup {
		groups = append(groups, g)
	}
	sort.Strings(groups)
	for _, g := range groups {
		es := byGroup[g]
		sort.Slice(es, func(i, j int) bool {
			if es[i].Title != es[j].Title {
				return es[i].Title < es[j].Title
			}
			return es[i].ID < es[j].ID
		})
		fmt.Fprintf(&b, "## %s\n\n", g)
		t := newTable(&b, "Title", "ID", "Key", "Hint")
		for _, e := range es {
			t.row(cell(e.Title), code(e.ID), humanKeys(e.Keys), code(e.Hint))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Commands added at run time\n\n")
	b.WriteString("The palette also shows commands that are not listed here:\n\n")
	b.WriteString("- **`User: <title>`** — your own shell commands from `~/.config/termocode/commands.json` " +
		"(open it with **Open Config: User Commands**). See [config files](config-files.md).\n")
	b.WriteString("- **`Ext: <title>`** — commands registered by Lua extensions in `~/.config/termocode/extensions/`. " +
		"Bind one to a key with `\"<key>\": \"ext:<command id>\"` in `keymap.json`.\n")
	b.WriteString("- Recently used commands move to the top of the list.\n")
	return b.String()
}

// ── settings.md ─────────────────────────────────────────────────────────

func renderSettings() string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("# Settings\n\n")
	b.WriteString("Settings live in `~/.config/termocode/config.json` (or `$XDG_CONFIG_HOME/termocode/config.json`). " +
		"Change them with **Preferences: Open Settings (UI)**, or edit the file by hand. " +
		"A missing key uses its default. Unknown keys are kept.\n\n")
	b.WriteString("```json\n{\n  \"theme\": \"vscode-dark-plus\",\n  \"tab_size\": 4,\n  \"word_wrap\": true\n}\n```\n\n")

	var order []string
	byCat := map[string][]app.SettingEntry{}
	for _, s := range app.SettingsCatalog() {
		if _, ok := byCat[s.Category]; !ok {
			order = append(order, s.Category)
		}
		byCat[s.Category] = append(byCat[s.Category], s)
	}
	for _, c := range order {
		fmt.Fprintf(&b, "## %s\n\n", c)
		t := newTable(&b, "Key", "Type", "Default", "Description")
		for _, s := range byCat[c] {
			t.row(code(s.Key), cell(s.Type), code(s.Default), cell(s.Description))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Environment variables\n\n")
	t := newTable(&b, "Variable", "Description")
	for _, e := range app.EnvCatalog() {
		t.row(code(e.Name), cell(e.Description))
	}
	return b.String()
}

// ── config-files.md ─────────────────────────────────────────────────────

func renderConfigFiles() string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("# Config files\n\n")
	b.WriteString("Every file termocode reads or writes. termocode never fails to start " +
		"because of a missing or broken file; it uses defaults instead.\n\n")

	sections := []struct{ loc, title, intro string }{
		{"config", "Config folder", "`~/.config/termocode/`, or `$XDG_CONFIG_HOME/termocode/`."},
		{"data", "Data folder", "`~/.local/share/termocode/`, or `$XDG_DATA_HOME/termocode/`."},
		{"workspace", "Workspace folder", "Inside the folder you open."},
		{"other", "Other files", ""},
	}
	files := app.ConfigFileCatalog()
	for _, s := range sections {
		fmt.Fprintf(&b, "## %s\n\n", s.title)
		if s.intro != "" {
			b.WriteString(s.intro + "\n\n")
		}
		t := newTable(&b, "File", "Purpose", "Format", "Safe to edit?")
		for _, f := range files {
			if f.Location == s.loc {
				t.row(code(f.Path), cell(f.Purpose), cell(f.Format), cell(f.Edit))
			}
		}
		b.WriteString("\n")
	}
	b.WriteString("**Preferences: Export Settings…** writes all config-folder JSON files into one bundle, " +
		"except state files (`session.json`, `recents.json`, `workspaces.json`, `palette_recents.json`) " +
		"and anything that looks like a secret.\n")
	return b.String()
}
